# Generated by Django 5.1.5 on 2025-02-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacci',
            name='fibonacci_value',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
